server:
  port: 8082

spring:
  application:
    name: api-gateway

  cloud:
    gateway:

      # ===============================
      # ROUTE DEFINITIONS
      # ===============================
      routes:

        # Auth Service (Public)
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
        
        # Me endpoint (Protected)
        - id: auth-me
          uri: http://localhost:8081
          predicates:
            - Path=/me/**

      # ===============================
      # GLOBAL CORS CONFIG (React)
      # ===============================
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      # Optional but useful
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

management:
  endpoints:
    web:
      exposure:
        include: health,info

auth:
  jwt:
    secret: CHANGE_THIS_TO_A_VERY_LONG_SECRET_KEY_1234567890